return {
	disable_booster_tag = false,
	only_ygo_cards = true,
	extra_ygo_booster = true,
	disable_tooltips = false,
	instant_poker_hand = false,
	disable_main_menu = false,
	disable_glow = false,
	disable_side_deck = true,
	alt_art = {
		j_joy_dmaid_house = false,
		j_joy_etwin_kisikil = false,
		j_joy_etwin_lilla = false,
		j_joy_dogma_ecclesia = false,
		j_joy_yokai_ash = false,
		j_joy_yokai_belle = false,
		j_joy_lab_lady = false,
		j_joy_eld_eldlich = false,
		j_joy_shaddoll_winda = false,
		j_joy_shaddoll_elconstruct = false,
		j_joy_invoked_aleister = false,
		j_joy_invoked_mechaba = false,
		j_joy_apollousa = false,
		j_joy_ipmasq = false,
	}
}
